### ISSUE TITLE
How to run the container with root  user?

### ISSUE THREAD

**Issue by qpb8023** [kasmtech/workspaces-images#1]
sudo docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/desktop:1.9.0 

How does this command add the root   option

**Comment by mmcclaskey** [comment]
If you want to run a container as root add the "--user root" argument, though, it is not recommended. If the reason to run as root is to install software, you should instead create a custom image, install everything you need on the custom image. Here is a guide on creating custom images.  https://kasmweb.com/docs/latest/how_to/building_images.html
