### ISSUE TITLE
How do I make the Brave browser image start as a Windows and not full screen?

### ISSUE THREAD

**Issue by Taomyn** [kasmtech/workspaces-images#106]
Sorry for the noob question, only been using Kasm for a short time, but I have the Brave browser image working nicely and as a persistent workspace but it always starts full screen. How can I make open as a Window preferably with the same dimensions as the last time it was run?

Opening full screen has the adverse effect of preventing popup windows or hiding them behind the main browser window, such as when I open an email on my webmail server and in other places.

Also, can I enable the window controls at the top e.g. close, maximise etc as this also causes closing pop up windows to be more difficult and less intuitive since that how I would normally do it.

**Comment by j-travis** [comment]
You'll need to build your own image.

Comment out these 3 lines of the dockerfile : https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-brave#L18-L21

Then you can review, modify this startup script as desired. You can see there are arguments to maximize the browser by default. Modify to your likeing.
https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/brave/custom_startup.sh
