### ISSUE TITLE
kali linux inside kasm images failed to pull

### ISSUE THREAD

**Issue by jamieduk** [kasmtech/workspaces-images#11]
Failed to pull image (kasmweb/chrome:1.10.0) : 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.10.0&fromImage=kasmweb%2Fchrome: Internal Server Error ("Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution")

**Comment by jamieduk** [comment]
still not been fixed?????

**Comment by j-travis** [comment]
Both of your errors indicate a DNS name resolution issue which is likely an issue with your environment and not the Kasm app.

Try pulling the image manually from the commandline

```
sudo docker pull kasmweb/core-kali-rolling:1.11.0
```

**Comment by TheBlindHacker** [comment]
When i installed (zima board) it defaulted to the small 32gb emmc. it has 2x4tb SSD's how can i send Kasm workspaces to a mount point there? is there a way in the app or do I need to use the actual FS?

**Comment by j-travis** [comment]
> When i installed (zima board) it defaulted to the small 32gb emmc. it has 2x4tb SSD's how can i send Kasm workspaces to a mount point there? is there a way in the app or do I need to use the actual FS?

https://www.reddit.com/r/kasmweb/comments/13611uz/comment/jimc7c1/?context=3&share_id=ZnDlX2rs9fzIwfagoS80L&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1
