### ISSUE TITLE
run teamview app failed

### ISSUE THREAD

**Issue by m986883511** [kasmtech/workspaces-images#12]
A very good project! I have same problem, i can‘t start teamviewer app.
![image](https://user-images.githubusercontent.com/34444109/153530804-759b932a-b997-4722-93ce-36b17d99a10e.png)

my dockerfile is :
`
FROM kasmweb/desktop:1.10.0-rolling
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

COPY teamviewer_15.26.4_amd64.deb .
RUN apt install libminizip1 libxcb-icccm4 libxkbcommon-x11-0 libxcb-xkb1 libxcb-xinerama0 libxcb-image0 libxcb-randr0 libxcb-keysyms1 libxcb-render-util0 -y
RUN dpkg -i *.deb
RUN apt install teamviewer

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
`

**Comment by OscarCy** [comment]
Same boat

**Comment by j-travis** [comment]
Hi @OscarCy , this was reported in our workspaces-issues repo as well.  The service required being ran as root. 

https://github.com/kasmtech/workspaces-issues/issues/155
