### ISSUE TITLE
Persistent plugin in Brave or Chrome browser

### ISSUE THREAD

**Issue by ccris02** [kasmtech/workspaces-images#17]
Would it be possible to install plugin in Brave or Chrome browser and then save that as a default image so the plugin would be always there?

I use KASM to look at Scam websites that are trying to steal crypto wallet information from users and I do need to use some whois plugin to get information about the domain registrar and name servers.

I use this plugin
https://chrome.google.com/webstore/detail/ip-address-and-domain-inf/lhgkegeccnckoiliokondpaaalbhafoa?hl=en

**Comment by j-travis** [comment]
We have examples docs on how you can use Chrome Managed Policies to ensure certain settings or extensions are automatically loaded when Chrome starts:
https://kasmweb.com/docs/latest/how_to/chrome_managed_policies.html

Hope this helps
