### ISSUE TITLE
How to set the language to simplified Chinese

### ISSUE THREAD

**Issue by laiqinghua** [kasmtech/workspaces-images#18]
This project is great!
I want to know how to set the language to simplified Chinese。
This project will be popular all over the world!

**Comment by laiqinghua** [comment]
And how to install Chinese input method

**Comment by j-travis** [comment]
Hi @laiqinghua ,
We have been working on adding automatic IME (Input Method Editor) support.  It will be available in the next release.

In the coming days we will start publishing our nightly developer builds. When that happens, you can try the feature right away.

Here is a teaser to the pre-release docs that demonstrate the feature and how its used.
https://kasmweb.com/docs/develop/how_to/ime.html

**Comment by laiqinghua** [comment]
That's great!
This perfectly solves our problem!
