### ISSUE TITLE
Standalone docker image kasmweb/gimp:1.10.0 loops, failing to start audio

### ISSUE THREAD

**Issue by aldobranti** [kasmtech/workspaces-images#22]
command is

`docker run -name kasmweb_gimp --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password -v /home/kasm-user/:/home/kasm-user/ kasmweb/gimp:1.10.0`

loops endlessly 

`------------------ Started Audio Out  ----------------------------
Kasm Audio Out PID: 769
/dockerstartup/vnc_startup.sh: line 220: kill: (769) - No such process
Restarting Audio Out Service
Starting audio server
Starting audio service`

Not that I want audio ... so is there an e/v to turn it off ?

**Comment by j-travis** [comment]
Ensure /home/kasm-user is owned by uid:gid 1000
```
sudo chown 1000:1000 -R /home/kasm_user
```

If you want to disable the audio services you can use the following environment variables
 `KASM_SVC_AUDIO=0` and `START_PULSEAUDIO=0`

**Comment by aldobranti** [comment]
thank you for the e/v settings 

WRT uid for kasm-user , regrettably when running this standalone on my NAS I find that another user already has uid 1000

Is this a deal breaker ? I can get as far as a VNC screen while running kasm-user with uid 1001

**Comment by aldobranti** [comment]
the 1.11.0 image gets through to a gimp application window
thank you for the assistance
