### ISSUE TITLE
Why is kasmweb/chrome `Managed by your organization`?

### ISSUE THREAD

**Issue by pmorch** [kasmtech/workspaces-images#27]
I've noticed that this is not a normal chome installation, but one that is managed by an organization:
![image](https://user-images.githubusercontent.com/159292/190903513-6c7e5bbd-8296-48e3-bd0c-46e12d2ee1e3.png)

It is normally only companies and malware that tries to manage my chrome. I really don't want outsiders to be able to control or snoop on my browsing.

So why is that? Who/what is that organization? And how do I remove that?

**Comment by j-travis** [comment]
Hi, this message shows anytime you use Chrome managed policies which is a helpful way of setting default configurations

Our images are open source, so you can see what we are doing.

- https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L16
- https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/chrome/install_chrome.sh#L90

Also, in general you can see what policies are assigned by navigating to `chrome://policy/` from within the browser

You are welcome to build your own images and add/remove policies as you see fit. Here are some resources to help.

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://youtu.be/BGP69_f1wq0

**Comment by pmorch** [comment]
Thanks
