### ISSUE TITLE
Why is kasm/chrome-flash and firefox-flash gone?

### ISSUE THREAD

**Issue by juanmartinbelda** [kasmtech/workspaces-images#28]
With yesterday's commit 4891a72f6c42770fdb8e4f80ec52ded218cabe3e both images are no longer available. Is there a chance that they will be available again?

If not is there a chance of obtaining instructions on how to add them manually?

I was using them to test flash legacy applications that will not be ported any time soon

**Comment by j-travis** [comment]
@juanmartinbelda ,
We no longer maintain these images so they were taken offline.
We've temporarily re-enabled the repository. Please pull the images, archive them or push a copy to your own registry.

We will take them offline again Monday.

Thanks for understanding

**Comment by juanmartinbelda** [comment]
Thanks a lot!  I've pulled the images and copy them to an internal server.

**Comment by juanmartinbelda** [comment]
Hi!

I don't have it anymore as they were broken. Never get them to work properly

**Comment by PHatezjwhw** [comment]
@juanmartinbelda ,
That's a pity. But I also encountered a lot of problems when using it. I thought I didn't get it at that time. Maybe it was not a complete finished product in the first place. I will think of other ways. Thank you for your reply.
