### ISSUE TITLE
any xfce docker image not working 

### ISSUE THREAD

**Issue by jakbin** [kasmtech/workspaces-images#29]
i tried many docker images but no one not working, 

Every time i try to run i got same error 

![error](https://user-images.githubusercontent.com/65591973/193518297-339f3968-cc75-4ac9-a2f9-23ad59693bfb.png)

![error](https://user-images.githubusercontent.com/65591973/193518321-bf2dabe1-63f5-4318-a40d-b70ec501b164.png)

![error](https://user-images.githubusercontent.com/65591973/193518352-339a0b77-1050-4458-a1b3-bc5d58979411.png)

**Comment by j-travis** [comment]
Try accessing the container via HTTPS: `https://127.0.0.1:6901`

**Comment by jakbin** [comment]
@j-travis that is working, thanks for reply.

**Comment by jakbin** [comment]
How run images in background, like container ?
