### ISSUE TITLE
I cannot change the language of inkscape it stay in english

### ISSUE THREAD

**Issue by yodatak** [kasmtech/workspaces-images#46]
With kasmweb/inkscape:1.12.0 language stay in english even i changed and restart what should i do report it to inkscape too ?

**Comment by j-travis** [comment]
You'll want to refer to the inskcape documentation to see if they support additional languages , and if so, how to change it. Sometimes programs will respect one of several environment variables like LANG or LANGUAGE,  Other times the application has its own configuration file
