### ISSUE TITLE
Docker Networks Not Shown

### ISSUE THREAD

**Issue by shape-err** [kasmtech/workspaces-images#51]
Following the [VPN Sidecar Container](https://kasmweb.com/docs/latest/how_to/vpn_sidecar.html#customizing-workspaces) guide, I have created a VPN container and docker network. However, when selecting "Restrict Image to Docker Network" within any Kasm Workspace, only bridge and kasm_default_network are listed.

![Screenshot_20230321_195451](https://user-images.githubusercontent.com/8568594/226776802-e92480c3-ed69-4690-aa3f-d9eaa5b5b5a5.png)

**Comment by j-travis** [comment]
Hi, this ticket belongs in https://github.com/kasmtech/workspaces-issues , Can you please report there and include all the requested information
