### ISSUE TITLE
docker build and run chrome ,access show black 

### ISSUE THREAD

**Issue by andyoulovexy** [kasmtech/workspaces-images#52]
![image](https://user-images.githubusercontent.com/38940994/227718124-febb474b-d2d5-49a0-80e1-a35f6e655555.png)

**Comment by j-travis** [comment]
What tag are you using? We are aware of this in the `:develop` tags and it should be fixed soon, but the `:1.12.0` and `:1.12.0-rolling` should be good.

Appreciate the feedback.

**Comment by j-travis** [comment]
Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling

https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1

**Comment by andyoulovexy** [comment]
> Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> 
> https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1

ok,i will try!!,tks

**Comment by andyoulovexy** [comment]
> Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> 
> https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1

I use 1.12.0-rolling,it does't work

![image](https://user-images.githubusercontent.com/38940994/227768082-555edd51-764f-480e-8f86-1023be175ee0.png)

**Comment by andyoulovexy** [comment]
> Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> 
> https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1

I changed to 1.12.0-rolling ,but had same error,browser does't work!!
![image](https://user-images.githubusercontent.com/38940994/227839085-ae1572c0-ff53-4973-a40f-7bf2e86841be.png)

**Comment by andyoulovexy** [comment]
> Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> 
> https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1

![image](https://user-images.githubusercontent.com/38940994/227874323-8cf69a90-d079-4d53-8498-5986a8b2958f.png)

**Comment by andyoulovexy** [comment]
please close it

**Comment by LYUYork** [comment]
> > Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> > https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1
> 
> ![image](https://user-images.githubusercontent.com/38940994/227874323-8cf69a90-d079-4d53-8498-5986a8b2958f.png)

I get the similar error, how to solve it?

1. images: 1.12.0 or 1.12.0-rolling

![Uploading 1707984682685.png…]()

1. images: 1.14.0 later
it's black

**Comment by LYUYork** [comment]
> > Sorry, I see you mentioned you were building - so yes its going to be pulling the develop tag of the core image. For a immediate workaround you can change this to 1.12.0 or 1.12.0-rolling
> > https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome#L1
> 
> ![image](https://user-images.githubusercontent.com/38940994/227874323-8cf69a90-d079-4d53-8498-5986a8b2958f.png)

I get the similar error, how to solve it?

- images: 1.12.0 or 1.12.0-rolling

<img width="1156" alt="1707984682685" src="https://github.com/kasmtech/workspaces-images/assets/45093086/363270f0-ac51-40cf-8d8f-908690008381">


- images: 1.14.0 later
it's black
