### ISSUE TITLE
I proxy to chrome and enable https by nginx

### ISSUE THREAD

**Issue by andyoulovexy** [kasmtech/workspaces-images#54]
I proxy to chrome and enable https by nginx,client didn't send any！！when I disable https,access normal.
![image](https://user-images.githubusercontent.com/38940994/228568187-7929b1b8-8a16-4847-be13-97671f13c506.png)

**Comment by xishian** [comment]
1. First, you can disable the basic authentication by -DisableBasicAuth
2. Or you can configure nginx, transfer the auth header to vnc server
