### ISSUE TITLE
Discord Image lacks support for OS-native emojis

### ISSUE THREAD

**Issue by EpicLPer** [kasmtech/workspaces-images#56]
The Discord image lacks all emojis that should be native to the OS, as example in channel- or usernames.

![image](https://user-images.githubusercontent.com/8442196/229100252-f20889ee-e72b-4f78-b9ac-b562277f6220.png)

The above channels should all have their own emoji attached to them in the beginning, like here.

![image](https://user-images.githubusercontent.com/8442196/229100683-29bd2b60-d4aa-4159-b857-caf6540a1f4f.png)

I'm not sure how hard of a fix this would be since it's a very slimmed down Linux in the background, but hope this can be addressed at some point :) Thanks already!

**Comment by EpicLPer** [comment]
Heya! In addition to the Reddit comment you guys made where the `fonts-noto-color-emoji` should be installed to make it work properly I also found the `fonts-noto-core` to be needed for a few letters a friend of mine used in his username, as example this: 𝕭𝖔𝖘𝖘

That also made his username work, so if possible maybe also include that in the image if it doesn't make it too "bloated" by that point then :) Thanks!

**Comment by j-travis** [comment]
Yes 
```
fonts-noto-core 
fonts-noto-cjk
fonts-noto-color-emoji
``` 
are included in the change, as well as additional locales to assist with running the sessions with alternate languages.

We are cutting the 1.13.0 release in the coming days, so this fix didnt make it, but as soon as we drop 1.13.0 we will push this font update to the images in the develop tag, so `kasmweb/discord:develop` and you'll be able to test with it.

And yes those fonts are big so they bloat the core images by about 10-15%.  We will monitor feedback and adjust accordingly

**Comment by j-travis** [comment]
Can you please try the develop tag of the discord image now `kasmweb/discord:develop` and see if this works for you
