### ISSUE TITLE
Ubuntu Focal 20.04 missing Print Server

### ISSUE THREAD

**Issue by EpicLPer** [kasmtech/workspaces-images#59]
Heya!

Just noticed that the Ubuntu Focal image is missing a print server, despite the printer configuration GUI being available in the Settings.
I tried to compile my own Docker image with cups and drivers installed, but sadly this didn't change anything and it's still reporting a "failed to connect to server" error.

Would there be a way to include this in future versions? Or how can one add this inside of a custom Docker container to work properly?

Thanks!

**Comment by j-travis** [comment]
We probably wont include cups running inside the main containers, but you can add it yourself.

Install cups and maybe the hp drivers. Add the kasm user to the lpadmin group
```
apt-get install -y  cups hplip
usermod -a -G lpadmin kasm-user
```

Then you could add a [Docker Exec Config](https://kasmweb.com/docs/latest/guide/workspaces.html#docker-exec-config) to start cups when the container is launched

```
{
 "first_launch":{
      "user":"root",
      "cmd":"bash -c 'cupsd'"
  }
}
```

**Comment by j-travis** [comment]
Only that command runs as root
