### ISSUE TITLE
Persistent bookmarks Firefox/Chrome

### ISSUE THREAD

**Issue by githubja-lab** [kasmtech/workspaces-images#60]
Hi, I was wondering what is the best approach for persistent bookmarks. I know that I should be able to do it using the custom images (embedding the bookmarks to the container) or persistent profiles, In terms of system usage and performance? 

Thank you,

**Comment by j-travis** [comment]
At the end of the day, if you want persistent bookmarks (meaning they are always present), you'll want to use the browser's policy settings.  You can either bake that into a custom image, or use the new file mapping feature available in Kasm 1.13.0. 

We have an example of doing this exact thing in the docs: 
https://kasmweb.com/docs/latest/how_to/chrome_managed_policies.html#file-mappings


There is essentially no performance or storage hit.

You'd want to add persistent profiles on top of this only if you want the end user to be able to retain their history or changes.  Any performance hit will come from if the storage location is on a different or network drive. and of course you will need to have enough storage for whatever the user saves
