### ISSUE TITLE
Skip Discord Host Update to prevent "Download Update" window

### ISSUE THREAD

**Issue by EpicLPer** [kasmtech/workspaces-images#61]
Heya!

This is more of an info than an issue, but I noticed on my custom compiled Workspace that Discord requires an update again. However I found a way to work around this and still be able to use Discord till the next update and not leave people stranded with a non-functioning client :)
Maybe you can implement this somehow in the Discord installer for other people to enjoy as well.

1. Open `.config/discord/settings.json`
2. Add the following entry: `"SKIP_HOST_UPDATE": true`

This prevents Discord from checking for a host installation update which prevents the whole client from functioning, and since the Docker images are updated periodically anyways this shouldn't be too big of a deal to use an outdated host install for a few days.

Hope this helps!

**Comment by j-travis** [comment]
This has been added to added and is visible in the develop tagged images
