### ISSUE TITLE
Libreoffice seems to require an additional path set to run

### ISSUE THREAD

**Issue by GadgetGeekNI** [kasmtech/workspaces-images#66]
Error using core-ubuntu-focal:1.13.0, using the standard install scripts from Kasm to install libreoffice in docker file..:

`# Install Libre Office #
COPY src/ubuntu/install/libre_office $INST_SCRIPTS/libre_office/
RUN bash $INST_SCRIPTS/libre_office/install_libre_office.sh  && rm -rf $INST_SCRIPTS/libre_office/`

In Desktop, Double-clicking Libreoffice, the icon appears briefly then disappears..

Trying it from CLI as below;

`default:~$ libreoffice
Xlib:  extension "XINERAMA" missing on display ":1.0".
/usr/lib/libreoffice/program/javaldx: error while loading shared libraries: libreglo.so: cannot open shared object file: No such file or directory
Warning: failed to read path from javaldx
/usr/lib/libreoffice/program/soffice.bin: error while loading shared libraries: libreglo.so: cannot open shared object file: No such file or directory
`

Running the below line fixes it via CLI.
`export LD_LIBRARY_PATH="/usr/lib/libreoffice/program:$LD_LIBRARY_PATH"`

I didn't see any other tickets about this so I wanted to log it here for reference.

**Comment by j-travis** [comment]
Thank you for reporting this.
Interestingly libre seems to be working fine in both of the locations we use it. 
- In the single app image.
- in the Alpine image.

But we've confirmed the issue you saw when trying to use it on a custom ubuntu build.  It looks like you figured it out, but a quick workaround is to add the following lines to your dockerfile after the libre install scripts

```
RUN sed -i 's@Exec=libreoffice@Exec=env LD_LIBRARY_PATH=:/usr/lib/libreoffice/program:/usr/lib/x86_64-linux-gnu/ libreoffice@g' ~/Desktop/libreoffice-startcenter.desktop
RUN sed -i 's@Exec=libreoffice@Exec=env LD_LIBRARY_PATH=:/usr/lib/libreoffice/program:/usr/lib/x86_64-linux-gnu/ libreoffice@g' /usr/share/applications/libreoffice-*.desktop
```

This will modify the desktop and application menu shortcuts with the required import

**Comment by GadgetGeekNI** [comment]
Thank you, 

I can confirm that this has fixed the issue. Much appreciated!

**Comment by j-travis** [comment]
This fix has been merged into the `:develop` tags of our images. It should be available in a few hours
