### ISSUE TITLE
dockerfile-kasm-chrome in Kubernetes Cluster

### ISSUE THREAD

**Issue by VijayanRamachandran** [kasmtech/workspaces-images#70]
Hi,

I tried below mentioned docker file to deploy it in our kubernetes cluster, by following below mentioned steps,
https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome

1. Build above docker and push to our custom container registry
2. Implemented deployment.yaml, service.yaml, and ingress.yaml ( together with nginx ingress controller )
3. Deployed the same in Cluster

When i send request ( start application using host defined in ingress ) i am facing below error, 
This information is from POD log.

 2023-07-18 11:48:19,548 [INFO] websocket 0: got client connection from 10.244.10.83
 2023-07-18 11:48:19,555 [DEBUG] websocket 0: using SSL socket
 2023-07-18 11:48:19,556 [DEBUG] websocket 0: X-Forwarded-For ip '10.83.193.134'
 2023-07-18 11:48:19,556 [INFO] websocket 0: Authentication attempt failed, BasicAuth required, but client didn't send any
 2023-07-18 11:48:19,556 [INFO] websocket 0: 10.244.10.83 10.83.193.134 - "GET / HTTP/1.1" 401 158
 2023-07-18 11:48:19,556 [DEBUG] websocket 0: No connection after handshake
 2023-07-18 11:48:19,556 [DEBUG] websocket 0: handler exit

Error talks about Authentication Attemp failed, BasicAuth required, but client didnt send any => Eventhough i have properly configured basic auth in ingress.

Here by i have attached, deployment.yaml, service.yaml, and ingress.yaml file for reference.

Can you please help regarding this ?

PS: 

1. Same problem i am facing for below mentioned dockers as well,
   https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-firefox
   https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-postman

2. If i deploy the same docker files ( above mentioned ) in docker desktop **without ingress** and with help of port-forward to service directly application is working fine as expected.
   This problem happens only if we enable ingress in cluster.

Note: 
As specified in ingress, secret is been set accordingly by generating auth file using htpasswd.

**Deployment.yaml**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasm-chrome
  labels:
    io.kompose.service: kasm-chrome
    commonappsaccess: ise
    appType: web
    app: kasm-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kasm-chrome
  strategy:
    type: Recreate
  template:
    metadata:      
      labels:        
        io.kompose.service: kasm-chrome
        commonappsaccess: ise
        appType: web
        app: kasm-chrome
    spec:
      imagePullSecrets:
        - name: **XXXXXXXXXX**
      containers:      
        - env:
            - name: VNC_PW
              value: "password"
          name: kasm-chrome
          image: xyz.azurecr.io/kasm-chrome:latest
          ports:
            - containerPort: 6901
      restartPolicy: Always

**service.yaml**

apiVersion: v1
kind: Service
metadata:
  name: kasm-chrome
  labels:
    io.kompose.service: kasm-chrome
    commonappsaccess: ise
spec:
  selector:
    io.kompose.service: kasm-chrome
    commonappsaccess: ise
    appType: web
  ports:
    - name: "6901"
      port: 6901
      targetPort: 6901

**Ingress.yaml**

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kasm-chrome-ingress
  labels:
    commonappsaccess: ise
  annotations:    
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "kasm-chrome"
    nginx.ingress.kubernetes.io/session-cookie-expires: "7200"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "7200"  
    nginx.ingress.kubernetes.io/proxy-body-size: 10k
    nginx.ingress.kubernetes.io/rewrite-target: /$1    
    **nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"**
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    **nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: kasm-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - kasm-chrome'**
spec:
  rules:
    - host: **xyz.com**
      http:
        paths:          
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kasm-chrome
                port:
                  number: 6901
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: kasm-chrome
                port:
                  number: 6901
  tls:
  - hosts:
    - kasm-chrome.shift-playgrounds.siemens-healthineers.com
    secretName: kasm-chrome-tls
 
**kasm-basic-auth.yaml**

apiVersion: v1
kind: Secret
type: Opaque
metadata:  
  name: kasm-basic-auth
data:
  auth: a2FzbV91c2VyOiRhcHIxJFkxN3ZWU1VrJEIuSTJWajBnaE9ySVZUczQ1N0E0TDA=

**Comment by j-travis** [comment]
Your best bet it to search the KasmVNC issues for folks putting kasmVNC behind a proxy and passing through basic auth
https://github.com/kasmtech/KasmVNC/issues

Merry that feedback with your configurations

**Comment by VijayanRamachandran** [comment]
Hi @j-travis 

Thanks for pointing it out.

I checked KasmVNC issue list and I could solve my issue based on already solved KasmVNC issue mentioned below,
https://github.com/kasmtech/KasmVNC/issues/29

Thanks & Regards,
Vijayan Ramachandran
