### ISSUE TITLE
[telegram] Automatically logs me out after a few days and then doesn't stay logged on

### ISSUE THREAD

**Issue by EpicLPer** [kasmtech/workspaces-images#76]
Heya,

I've had this issue for quite a while now, I'm mainly using Telegram inside a custom Ubuntu Focal workspace but I guess this would also happen for the standalone container.

After a few days Telegram automatically logs me out, usually it stays logged in even after I delete the session. After logging into Telegram again and deleting the workspace it stays logged out and won't automatically log me in anymore.  
I'm not entirely sure why this is happening, but could it be that Telegram tries to do an automatic update in the background and due to the nature of Docker it simply can't write some files successfully?

I always have to rebuild my custom Docker image for it to work again for a few days, after which it'll just stop again.

Thanks already!

**Comment by j-travis** [comment]
Cana you review this ticket please. This is likely what you are bumping in to https://github.com/kasmtech/workspaces-issues/issues/395#issuecomment-1561090297

**Comment by EpicLPer** [comment]
Sorry for the late reply, but yes this seems to be the fix so far! Thanks ^^
