### ISSUE TITLE
VNC upload/download button do not appear on side bar when using docker image

### ISSUE THREAD

**Issue by shkpk** [kasmtech/workspaces-images#8]
I'm using [ubuntu desktop container](https://hub.docker.com/r/kasmweb/ubuntu-bionic-desktop) however I do not see upload/download button in side bar as it appears in some of your videos to upload and download files from desktop via vnc.
Is this something specific when using kasm workspace ? and not for container images?

**Comment by mmcclaskey** [comment]
Hello. If you are using the container directly using docker run, for example, you will be missing upload/download, audio in, and audio out. Then you need to run the full Kasm Workspaces platform. The community edition is free for up to 5 concurrent sessions. The platform has a lot of capability, such as user auth (LDAP, SAML, etc), central logging, redundancy, auto scaling, etc.

Download here
https://www.kasmweb.com/downloads.html

Install Docs here
https://www.kasmweb.com/docs/latest/install/single_server_install.html
