### ISSUE TITLE
Can't access Yahoo and Ebay on kasm workspaces browsers. 

### ISSUE THREAD

**Issue by awab-hassan** [kasmtech/workspaces-images#82]
Hello,

I have a VPS running in interserver US, I am running kasm workspace in kubernetes through deployment. I have installed 4 browsers; Edge, Chrome, Firefox, Brave. I can't access yahoo and ebay on browsers, whenever I try to load website it keeps on loading and then it says check your internet connection.

This is the **error:**
default:~$ curl -vvvv https://www.yahoo.com
*   Trying 74.6.143.25:443...
* TCP_NODELAY set
* Connected to www.yahoo.com (74.6.143.25) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):

interserver kasm (MY VPS ERROR)
default:~$ curl -vvvv https://www.yahoo.com
*   Trying 74.6.143.25:443...
* TCP_NODELAY set
* Connected to www.yahoo.com (74.6.143.25) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):

It is running fine on AWS: (this is the logs of AWS) 
AWS kasm
*   Trying -------------
* TCP_NODELAY set
* Connected to www.yahoo.com (-------) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Sunnyvale; O=Oath Holdings Inc.; CN=yahoo.com
*  start date: Sep 26 00:00:00 2023 GMT
*  expire date: Mar 20 23:59:59 2024 GMT
*  subjectAltName: host "www.yahoo.com" matched cert's "*.yahoo.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5568fc510300)
> GET / HTTP/2
> Host: www.yahoo.com
> user-agent: curl/7.68.0
> accept: /
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200

**Comment by j-travis** [comment]
Sorry, we don't have a supported K8s install, so this isn't something we can help with.

It sounds similar to this: https://github.com/kasmtech/workspaces-issues/issues/460 , so my recommendation would be the same.

Are you following a guide to work Kasm in K8s? If so can you share it
