### ISSUE TITLE
TOR Installation URL no longer working in Ubuntu

### ISSUE THREAD

**Issue by GadgetGeekNI** [kasmtech/workspaces-images#84]
TOR_URL is returning empty when trying to build my own image using the examples.

Below is a BB pipeline output.

 TOR_URL=
+ FULL_TOR_URL=https://www.torproject.org/
+ wget --quiet https://www.torproject.org/ -O /tmp/torbrowser.tar.xz
+ tar -xJf /tmp/torbrowser.tar.xz -C /home/kasm-default-profile/tor-browser/
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c bash $INST_SCRIPTS/torbrowser/install_torbrowser.sh  && rm -rf $INST_SCRIPTS/torbrowser/' returned a non-zero code: 2
2023-10-27T08:17:20.556618323Z stdout P 

I can confirm in a bash CLI, $TOR_URL is returning empty.

**Comment by GadgetGeekNI** [comment]
Odd but removing 64 from
`| grep linux64 | `works in the command line

`TOR_URL=$(curl -q https://www.torproject.org/download/ | grep downloadLink | grep linux | sed 's/.*href="//g'  | cut -d '"' -f1 | head -1)`

Testing out a rebuild now to see if it fixes the issue.

**Comment by GadgetGeekNI** [comment]
That seems to have worked on Ubuntu Focal.

Replace line 12 `  TOR_URL=$(curl -q https://www.torproject.org/download/ | grep downloadLink | grep linux64 | sed 's/.*href="//g'  | cut -d '"' -f1 | head -1)`

With `  TOR_URL=$(curl -q https://www.torproject.org/download/ | grep downloadLink | grep linux | sed 's/.*href="//g'  | cut -d '"' -f1 | head -1)`

**Comment by j-travis** [comment]
Thank you. This issue has been resolved and merged.
Our rolling pipelines will pick up the changes tonight and updated rolling tags will be produced with the latest version of TorBrowser.
