### ISSUE TITLE
Brave Browser Outdated

### ISSUE THREAD

**Issue by jalsarraf0** [kasmtech/workspaces-images#91]
I'm trying to figure out a way if I can update Brave browser in my Kasm Workspaces. Is this by design or is there another way around this?

**Comment by j-travis** [comment]
I'm not sure what you mean.
If you just want the updated brave version, try using our rolling tags.  Its built nightly and should include the latest version

e.g `kasmweb/brave:1.14.0-rolling`

https://hub.docker.com/r/kasmweb/brave/tags

**Comment by jalsarraf0** [comment]
Sorry if I wasn't clear enough. In the image it's showing my Brave broswer is out of date. I am using Kasm Workspaces and pulling Brave off of the registary.

![image](https://github.com/kasmtech/workspaces-images/assets/19882582/9eb2a175-7d7e-44c4-be44-53fdc8904cbe)

**Comment by j-travis** [comment]
The rolling tags are not the default when you install images from the registry. You'll need to edit the workspace entry and change the tag to rolling:

![image](https://github.com/kasmtech/workspaces-images/assets/48762190/a48657ee-480c-4112-98b3-5da0514f65d4)

![image](https://github.com/kasmtech/workspaces-images/assets/48762190/259df37c-b975-4aa1-aefa-8a3226580734)
